#!/usr/bin/env python3

import json
import locale
import sys
import reports
import emails

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"sales": 0, "model": ""}
  best_year = {}
  for item in data:
    year = item["car"]["car_year"]
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales X
    if item["total_sales"] > max_sales["sales"]:
      max_sales["sales"] = item["total_sales"]
      max_sales["model"] = item["car"]["car_model"]
    # TODO: also handle most popular car_year
    if year not in best_year:
      best_year[year] = item["total_sales"]
    elif year in best_year:
      best_year[year] += item["total_sales"]
  sortedYear = sorted(best_year.items() , reverse=True, key=lambda v: v[1])
  summary = """The {} generated the most revenue: ${} <br/>The {} had the most sales: {} <br/>The most popular year was {} with {} sales.""".format(format_car(max_revenue["car"]), max_revenue["revenue"],max_sales["model"], max_sales["sales"], sortedYear[0][0], sortedYear[0][1])

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  tableData = cars_dict_to_table(data)
  print(summary)
  # TODO: turn this into a PDF report
  reports.generate("/tmp/cars.pdf", "cars", summary, tableData)
  # TODO: send the PDF report as an email attachment
  email = emails.generate(sender, recipient, subject, body, attachment_path)
  emails.send(email)

if __name__ == "__main__":
  main(sys.argv)
